server.port=8080

external.api.base-url=https://eccdn.com.au
external.api.path=/misc/challengedata.json
external.api.timeout=5

logging.level.org.springframework.web=INFO
logging.level.com.example=DEBUG

